services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: educollab
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://admin:mysecretpassword@db:5432/educollab
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: admin
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_SQL_API_URL=http://api:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  hardhat:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "apk add --no-cache python3 make g++ && npm install && npx hardhat node --hostname 0.0.0.0"
    ports:
      - "8545:8545"

volumes:
  pgdata:
# s1 docker-compose up -d
# s2 docker exec -it blockchain-hardhat-1 ./node_modules/.bin/hardhat ignition deploy ignition/modules/SmartContract.js --network localhost
# tuy chon docker-compose logs -f hardhat / api / frontend de xem log